language: python

dist: xenial

python:
  - '3.7'

install:
  - pip install --upgrade setuptools pip
  - pip install cython
  - pip install -r requirements.txt
  - pip install qgrid
  - pip install nbval
  - pip install git+git://github.com/Leguark/scikit-image@master
  - pip install vtk
  - pip install pyevtk
  - pip install dataclasses emg3d pyvista panel discretize


script:

  - pytest -v notebooks/integrations/ --nbval-lax
  - pytest -v notebooks/examples/ --nbval-lax --current-env --ignore-glob='Topography*' --ignore-glob='Alesmodel*'
  - pytest -v notebooks/tutorials/ --nbval-lax --current-env --ignore-glob='ch1-6*' --ignore-glob='ch1-7*'
  - pytest

sudo: required
cache: pip

#before_script: # configure a headless display to test plot generation
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start